INSERT INTO bulletin(name,url,type,created,updated) values('Golang 官网','http://golang.org',0,curtime(),curtime());
INSERT INTO bulletin(name,url,type,created,updated) values('Golang China','http://studygolang.com',0,curtime(),curtime());
INSERT INTO bulletin(name,url,type,created,updated) values('Golang 中国','http://golangtc.com',0,curtime(),curtime());
INSERT INTO bulletin(name,url,type,created,updated) values('WeTalk社区','http://bbs.go-china.org',0,curtime(),curtime());
INSERT INTO bulletin(name,url,type,created,updated) values('Go Walker','http://gowalker.org',0,curtime(),curtime());
INSERT INTO bulletin(name,url,type,created,updated) values('关于社区的发展，请多多支持！','http://golanghome.com/post/16',1,curtime(),curtime());
INSERT INTO bulletin(name,url,type,created,updated) values('大家可以自定义头像啦！','http://golanghome.com/post/92',1,curtime(),curtime());
INSERT INTO bulletin(name,url,type,created,updated) values('关于申请创建新的话题的说明！','http://golanghome.com/post/122',1,curtime(),curtime());
INSERT INTO bulletin(name,url,type,created,updated) values('XORM - 简单而强大的Go语言ORM框','http://xorm.io',2,curtime(),curtime());
INSERT INTO bulletin(name,url,type,created,updated) values('Beego - 国内最好的Go Web开发框架','http://beego.me',2,curtime(),curtime());
INSERT INTO bulletin(name,url,type,created,updated) values('Gogs - Go 语言编写的自助 Git 托管服务','http://gogs.io',2,curtime(),curtime());
INSERT INTO bulletin(name,url,type,created,updated) values('Go轻松学 豌豆荚下载','http://www.wandoujia.com/app/net.duokr.goquicklearn',3,curtime(),curtime());
INSERT INTO bulletin(name,url,type,created,updated) values('Go轻松学 小米商店下载','http://app.mi.com/detail/54217',3,curtime(),curtime());
INSERT INTO bulletin(name,url,type,created,updated) values('Go轻松学 美国AppStore','https://itunes.apple.com/us/app/go-qing-song-xue/id882521751?ls=1&amp;mt=8',3,curtime(),curtime());
INSERT INTO bulletin(name,url,type,created,updated) values('Go轻松学 中国AppStore','https://itunes.apple.com/cn/app/go-qing-song-xue/id882521751?l=en&amp;mt=8',3,curtime(),curtime());